### ISSUE TITLE
Upgrade to 3.7?

### ISSUE THREAD

**Issue by jamesfalkner** [RedHat-Middleware-Workshops/modernize-apps-katacoda#1]
@BenHall @tqvarnst Should we upgrade the version of openshift-middleware used for this roadshow to 3.7? I'll need it for the istio lab/demo. 

The 3.7 playground image (openshift-3-7) is too limited to be useful for istio, which requires at least 4G of RAM.

**Comment by tqvarnst** [comment]
@BenHall I know that we initially said that 3.6 should be ok, but since James is now looking at Istio as well can we upgrade to 3.7 cluster just like Siamaks workshop?

**Comment by tqvarnst** [comment]
By the way this is not the openshift-middleware, so please do not update that yet (we'll handle that in a separate issue). This image doens't seem to have OpenShift installed at all. Can you please add OpenShift 3.7 to this image?

**Comment by BenHall** [comment]
This is on the dev server. Please verify it includes everything you expect. Once happy, I can promote to the cluster.
