### ISSUE TITLE
"coolstore-prod" project pods also need to stop in order to save resources.

### ISSUE THREAD

**Issue by bysnupy** [RedHat-Middleware-Workshops/modernize-apps-katacoda#10]
* Where: "Install Istio" section in tokyo/resilient-apps.
* Report:  "coolstore-prod" project pods were not included in the stopping pods list.

I executed the follow commands to stop pods in "coolstore-prod" project in order to save the resources.
I thought it's better to add below commands to the stopping pods list as well. 

```
oc scale --replicas=0 dc/coolstore-prod -n coolstore-prod
oc scale --replicas=0 dc/coolstore-prod-postgresql -n coolstore-prod
oc scale --replicas=0 dc/jenkins -n coolstore-prod
```

**Comment by jamesfalkner** [comment]
Thanks! I also noticed this but didn't think about adding jenkins to the list, so thanks for that! Fixed in f7ca0f74f939fad21dbe0f6e636273f8a99b3860
