### ISSUE TITLE
using outdated istio

### ISSUE THREAD

**Issue by jamesfalkner** [RedHat-Middleware-Workshops/modernize-apps-katacoda#13]
@BenHall does this workshop and the middleware workshops on learn.openshift.com share the same base image? Wondering if its safe to update to istio 0.6.0 here.

**Comment by BenHall** [comment]
No, I kept them independent so they can move at difference paces. I can upgrade if you wish?

**Comment by jamesfalkner** [comment]
OK. The lab was run in north america yesterday, and particpants reported that istio 0.6.0 was somehow present as a result of the `istio-install.sh` script (which forces `ISTIO_VERSION=0.4.0` in this lab scenario).. I am double-checking with the staff to find out if it really was the case.

**Comment by jamesfalkner** [comment]
OK I don't know what happened, but in any case it works for me with 0.4.0. I'll issue a PR which can be your notice that it's time to upgrade to 0.6.0 in the base image. standby for PR! After I resolve the ordering issue from the learn-openshift repo.

**Comment by jamesfalkner** [comment]
I went ahead and merged 411b496b9194978b4995379d4de2bde4952482eb so please upgrade to istio 0.6.0 in the base image. Thanks @BenHall !

**Comment by jamesfalkner** [comment]
@BenHall can this be closed? has the image been updated to have 0.6.0 pre-installed/pulled?

**Comment by BenHall** [comment]
Yes, Istio 0.6.0 has been deployed.
