### ISSUE TITLE
Moving an existing application to the cloud - Typo

### ISSUE THREAD

**Issue by Mustard** [RedHat-Middleware-Workshops/modernize-apps-katacoda#17]
In the moving an existing application to the cloud module the word "vontains" is in multiple locations, is this supposed to be "contains" ?

**Comment by jamesfalkner** [comment]
Yep, nice catch, thanks :) Fixed with https://github.com/RedHat-Middleware-Workshops/modernize-apps-katacoda/commit/a2e3b50730fae5061d2ba0fec2c77e5327f5ab15
