### ISSUE TITLE
Landing page for Monoliths to Microservices: App Transformation Hands-on Technical Workshop

### ISSUE THREAD

**Issue by tqvarnst** [RedHat-Middleware-Workshops/modernize-apps-katacoda#2]
Just like the Cloud Native workshop we need a landing page for each city we run the workshop in. @BenHall Can you provide an example from the Cloud native workshop?

**Comment by BenHall** [comment]
The site is already in the repo at https://github.com/RedHat-Middleware-Workshops/modernize-apps-katacoda/tree/master/branded-ui/katacoda

I still need the domain name for the project to make it live.
