### ISSUE TITLE
Lab code should be a git repository

### ISSUE THREAD

**Issue by jamesfalkner** [RedHat-Middleware-Workshops/modernize-apps-katacoda#6]
The code for the labs is in our [labs repo](https://github.com/RedHat-Middleware-Workshops/modernize-apps-labs) and needs to survive as a Git repo in the katacoda image.

Currently it is not:
```
[root@master monolith]# pwd
/root/monolith
[root@master monolith]# git status
fatal: Not a git repository (or any of the parent directories): .git
```
We are adding more subdirectories to the git repo next to `monolith` so ideally this would be cloned as a git repo in the image. Something like

```
cd ~
git clone https://github.com/RedHat-Middleware-Workshops/modernize-apps-labs projects
```

That way the subdirs will be present in ~/projects at:

`~/projects/monolith`
`~/projects/inventory` (does not yet exist; will be created soon)
`~/projects/catalog` (does not yet exist; will be created soon)

In our scenario scripts we will be doing a `git pull` to update the code with last minute changes, but to do that they need to be a true git repo. cc @tqvarnst

**Comment by BenHall** [comment]
```
[root@master ~]# tree -L 2
.
├── jboss-eap-7.1.0.zip
├── projects
│   ├── monolith
│   └── README.md
└── rhamt-cli-4.0.0.Beta4
    ├── addons
```
