### ISSUE TITLE
"oc login" does not work

### ISSUE THREAD

**Issue by jamesfalkner** [RedHat-Middleware-Workshops/modernize-apps-katacoda#7]
After letting the ansible script complete on `host02`, I am unable to login to OpenShift:

```
[root@master ~]# oc login
error: x509: certificate signed by unknown authority - verify you have provided the correct host and port and that the server is currently running.
error: x509: certificate signed by unknown authority
```

The only way I have found to login is with `oc login https://localhost:8443 --insecure-skip-tls-verify` - it would be nice to be able to login with `oc login` alone as is done in every other scenario I've ever seen on Katacoda.

**Comment by BenHall** [comment]
This is related to https://github.com/openshift-roadshow/cloud-native-katacoda/issues/24

I've read all of the 3.7 best practices and the configuration looks to be correct. I'm not sure on potential fixes.

When logging in, you need to specify the masterPublicURL.

Example https://github.com/openshift-roadshow/cloud-native-katacoda/blob/master/scenarios/getting-started/01-login.md

**Comment by jamesfalkner** [comment]
Added workaround. Not a huge deal so I think we can close this.
