### ISSUE TITLE
update istio docker images

### ISSUE THREAD

**Issue by jamesfalkner** [RedHat-Middleware-Workshops/modernize-apps-katacoda#8]
I've moved to the latest version of istio (0.4.0) and tested it - can you change the pre-pull logic to pull these now instead of the 0.3.0 versions. I've also added jaeger to the mix:

```
docker pull istio/istio-ca:0.4.0
docker pull istio/grafana:0.4.0
docker pull istio/pilot:0.4.0
docker pull istio/proxy_debug:0.4.0
docker pull istio/proxy_init:0.4.0
docker pull istio/mixer:0.4.0
docker pull istio/servicegraph:0.4.0
docker pull jaegertracing/all-in-one:latest
```

Thank you! I don't expect to do this again as the next version of Istio isn't due out until late Jan.

**Comment by BenHall** [comment]
This has been updated
